site_name: jimmy
site_description: A tool to import your notes from various formats to Markdown.

# Repository
repo_name: marph91/jimmy
repo_url: https://github.com/marph91/jimmy

theme:
  name: material
  # add open graph metadata (for example for discourse links)
  # https://mrkeo.github.io/reference/meta-tags/#customization
  custom_dir: docs/overrides
  features:
    # index.html for collapsible sections
    - navigation.indexes
    # show breadcrumbs
    - navigation.path
    # use more space for content and less for the toc
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration
    - toc.integrate
  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

plugins:
  # show last updated at bottom
  - git-revision-date-localized
  # open external links in a new tab
  - open-in-new-tab
  - search
markdown_extensions:
  - admonition
  # code block highlighting
  - pymdownx.superfences
  # disable the toc, since there is not that much content
  # https://github.com/squidfunk/mkdocs-material/discussions/2644#discussioncomment-715040
  - toc:
      permalink: true
      toc_depth: 0

# Page tree
nav:
  - index.md
  - Formats:
    - Default Import: formats/default.md
    - Bear: formats/bear.md
    - Cacher: formats/cacher.md
    - CherryTree: formats/cherrytree.md
    - Clipto: formats/clipto.md
    - Day One: formats/day_one.md
    - Dynalist: formats/dynalist.md
    - Facebook: formats/facebook.md
    - FuseBase: formats/fusebase.md
    - Google Keep: formats/google_keep.md
    - Joplin: formats/joplin.md
    - jrnl: formats/jrnl.md
    - Notion: formats/notion.md
    - Obsidian: formats/obsidian.md
    - QOwnNotes: formats/qownnotes.md
    - RedNotebook: formats/rednotebook.md
    - Simplenote: formats/simplenote.md
    - Standard Notes: formats/standard_notes.md
    - Synology Note Station: formats/synology_note_station.md
    - Textbundle: formats/textbundle.md
    - Tiddlywiki: formats/tiddlywiki.md
    # TODO
    # - Todo.txt: formats/todo.txt.md
    # - Todoist: formats/todoist.md
    - Tomboy-ng: formats/tomboy_ng.md
    # - Toodledo: formats/toodledo.md
    - vCard: formats/vcard.md
    # - xit: formats/xit.md
    - Zoho Notebook: formats/zoho_notebook.md
  - Import Instructions: import_instructions.md
  - Additional features:
    - Filters: additional_features/filters.md
    - Show the Note Tree: additional_features/show_note_tree.md
  - Contributing:
    - How to Contribute?: contributing/contributing.md
    - More Note Apps: contributing/more_note_apps.md
