site_name: jimmy

# Repository
repo_name: marph91/jimmy
repo_url: https://github.com/marph91/jimmy

theme:
  name: material
  features:
    # index.html for collapsible sections
    - navigation.indexes
    # show breadcrumbs
    - navigation.path
  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

plugins:
  # show last updated at bottom
  - git-revision-date-localized
  # open external links in a new tab
  - open-in-new-tab
  - search
markdown_extensions:
  - admonition
  # code block highlighting
  - pymdownx.superfences

# Page tree
nav:
  - index.md
  - Formats:
    - Default Import: formats/default.md
    - Bear: formats/bear.md
    - Clipto: formats/clipto.md
    - Dynalist: formats/dynalist.md
    - FuseBase: formats/fusebase.md
    - Google Keep: formats/google_keep.md
    - Joplin: formats/joplin.md
    - Notion: formats/notion.md
    - Obsidian: formats/obsidian.md
    - Simplenote: formats/simplenote.md
    - Standard Notes: formats/standard_notes.md
    - Synology Note Station: formats/synology_note_station.md
    - Textbundle: formats/textbundle.md
    - Tiddlywiki: formats/tiddlywiki.md
    - Todo.txt: formats/todo.txt.md
    - Todoist: formats/todoist.md
    - Toodledo: formats/toodledo.md
    - xit: formats/xit.md
    - Zoho Notebook: formats/zoho_notebook.md
  - Contributing:
    - Contributing: contributing/index.md