name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Build executable with pyinstaller
        run: python -m PyInstaller jimmy.spec
      - uses: actions/upload-artifact@v4
        # upload artifacts only if it's a release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: jimmy-${{ matrix.os }}
          path: ./dist/jimmy*
      - name: Smoke test
        run: |
          ./dist/jimmy test_inputs --dry-run
          ./dist/jimmy test_inputs/obsidian_vault --app obsidian --dry-run
