name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Build executable with pyinstaller
        run: python -m PyInstaller src/joplin_custom_importer.py --onefile --collect-data pypandoc
      - uses: actions/upload-artifact@v4
        with:
          name: joplin-custom-importer-${{ matrix.os }}
          path: ./dist/joplin_custom_importer*
      - name: Smoke test
        run: ./dist/joplin_custom_importer test_inputs --dry-run
