name: build

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      PYTHONPATH: src
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Build executables with pyinstaller
        run: |
          python -m PyInstaller jimmy_cli.spec
          # python -m PyInstaller jimmy_gui.spec
      - name: Install test dependencies
        run: pip install -r requirements-dev.txt
      - name: Create the test inputs (don't run the tests itself)
        run: python test/test_app.py
      - name: Smoke test
        run: |
          ./dist/jimmy-cli* .cache/arbitrary_folder/arbitrary_folder --dry-run
          ./dist/jimmy-cli* .cache/obsidian/obsidian_vault --format obsidian --dry-run
      - name: Release
        uses: softprops/action-gh-release@v2
        # release only if there is a release tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: ./dist/jimmy*
