name: tests

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pip dependencies
        run: |
          pip install -r requirements/requirements-dev.txt
          python -c 'from pypandoc.pandoc_download import download_pandoc; download_pandoc(version="3.4")'
      - name: install optional system depencencies
        run: sudo apt install -y asciidoctor
      - name: Run tests
        run: ./test.sh
